package com.nezuko.composeplayer.app.ui.nav

object RoutesNames {
    const val MAIN_SCREEN = "MAIN_SCREEN"
    const val SEARCH_SCREEN = "SEARCH_SCREEN"
    const val MY_LIBRARY_SCREEN = "MY_LIBRARY_SCREEN"
    const val PLAYLIST_SCREEN = "PLAYLIST_SCREEN"
    const val START_SCREEN = "START_SCREEN"
    const val SIGN_IN_SCREEN = "SIGN_IN_SCREEN"
    const val SIGN_UP_SCREEN = "SIGN_UP_SCREEN"
    const val CONTROL_PLAYING_TRACK_SCREEN = "CONTROL_PLAYING_TRACK_SCREEN"
    const val REGISTER_PROFILE_SCREEN = "REGISTER_PROFILE_SCREEN"
    const val PROFILE_SCREEN = "PROFILE_SCREEN"
    const val CROP_IMAGE_SCREEN = "CROP_IMAGE_SCREEN"
}